---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
rvm:
  - 1.8.7
  - 1.9.3
  - 2.1.1
  - jruby-19mode
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 3.7.0"
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: 1.8.7
